# DigitalOcean App Platform Configuration for Tenant Portal
# Deploy with: doctl apps create --spec .doctl-app.yaml
# Update with: doctl apps update <APP_ID> --spec .doctl-app.yaml

name: tenant-portal
region: nyc

services:
  - name: portal
    dockerfile_path: Dockerfile
    github:
      repo: altunumut24/tenant-portal
      branch: main
      deploy_on_push: true

    http_port: 8080

    # Minimal resources - perfect for a simple redirect service
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month - 512MB RAM, 1 vCPU

    routes:
      - path: /

    health_check:
      http_path: /healthz
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

    envs:
      # Default target URL (Beyaz Fırın)
      - key: TARGET_URL
        value: "https://beyaz-firin-mn2nr.ondigitalocean.app/"

